#
# Build image for blockpress.me.
#
FROM hkjn/golang

ENV CGO_ENABLED=0
WORKDIR /home/go/src/hkjn.me/blockpress.me/
COPY *.go ./
COPY ["vendor", "./vendor"]
COPY ["redirector", "./redirector"]
RUN go vet && \
    go install && \
    go install ./redirector/...
USER root
WORKDIR /home/go/bin
CMD ["mv", "-v", "blockpress.me", "redirector", "/build/"]

