#
# Build image for blockpress.me.
#
FROM hkjn/golang

ENV CGO_ENABLED=0
WORKDIR /home/go/src/hkjn.me/blockpress.me/
COPY *.go ./
COPY ["vendor", "./vendor"]
RUN go vet && \
    go install
USER root
CMD ["mv", "-v", "/home/go/bin/blockpress.me", "/build/"]

